spring:
  datasource:
    url: jdbc:postgresql://db:5434/${API_POSTGRES_DB}
    username: ${API_POSTGRES_USER}
    password: ${API_POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
    contexts: runtime