spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: Tbank Queue API

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog.xml

server:
  port: 8081